name: 'VIPS'
description: 'Compress and optimize images in your repository'
author: 'bitpatty'
inputs:
  github-token:
    description: 'GitHub access token'
    required: true
runs:
  using: 'composite'
  steps:
    - uses: actions/setup-node@v3
      with:
        node-version: '20.2.0'
    - run: sudo apt-get update && apt install -y libvips-tools
      shell: bash
    - run: npm install
      shell: bash
    - run: npm run build
      shell: bash
    - run: node dist/index.js
      shell: bash
