name: 'VIPS'
description: 'Compress and optimize images in your repository'
author: 'bitpatty'
inputs:
  token:
    description: 'GitHub access token'
    required: true
runs:
  using: 'composite'
  steps:
    - uses: actions/setup-node@v3
      with:
        node-version: '20.2.0'
        github-token: ${{ inputs.token }}
    - run: sudo apt-get update && sudo apt install -y libvips-tools
      shell: bash
    - run: cd ${{ github.action_path }} && npm install
      shell: bash
    - run: cd ${{ github.action_path }} && npm run build
      shell: bash
    - run: cd ${{ github.action_path }} && node ./dist/index.js
      shell: bash
