version: '3.7'

networks:
  vips-github-action-network:
    name: vips-github-action-network
    driver: bridge

services:
  application:
    container_name: vips-github-action
    build:
      context: .
      dockerfile: Dockerfile
      args:
        VARIANT: 20
        USER_UID: 1000
        USER_GID: 1000
    networks:
      - vips-github-action-network
    volumes:
      - ..:/workspace:cached
      - ~/.ssh:/home/node/.ssh:ro
      - /var/run/docker.sock:/var/run/docker.sock
    command: sleep infinity
    user: node
    env_file:
      - ./workspace.env
